# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sp < Formula
  desc "Sourceplane CLI - Infrastructure as Code orchestration"
  homepage "https://github.com/sourceplane/sourceplane"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.1/sp_0.1.1_darwin_amd64.tar.gz"
      sha256 "f16e7d7d7e55b57fd24b81c775e1897d8e63a174f781dc41ca57e599debf8c77"

      def install
        bin.install "sp"
      end
    end
    on_arm do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.1/sp_0.1.1_darwin_arm64.tar.gz"
      sha256 "a59a3bee232a02ac0f24c535e00da7f72c494b94b8d5a52eca8792808bd2c7d3"

      def install
        bin.install "sp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.1/sp_0.1.1_linux_amd64.tar.gz"
        sha256 "aaec0193ba19098ee4f47795edbd33bde09547d687698028cd4b79e5d5efabee"

        def install
          bin.install "sp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.1/sp_0.1.1_linux_arm64.tar.gz"
        sha256 "db85e47e6e74ede724c7d9288ffd2220b2012179587f9ba3fdd4aa72d8ba9371"

        def install
          bin.install "sp"
        end
      end
    end
  end

  test do
    system "#{bin}/sp version"
  end
end
