# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sp < Formula
  desc "Sourceplane CLI - Infrastructure as Code orchestration"
  homepage "https://github.com/sourceplane/sourceplane"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.4/sp_0.1.4_darwin_amd64.tar.gz"
      sha256 "0c9d7ee2fe2fe8db1a8725f0b28bb09d36f1dcd232e10560e19648a8333b6d45"

      def install
        bin.install "sp"
      end
    end
    on_arm do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.4/sp_0.1.4_darwin_arm64.tar.gz"
      sha256 "7afb42f7b467878851bd31c6e1dc1c1e87cf956af15f97d5cb7ba63c26a484b7"

      def install
        bin.install "sp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.4/sp_0.1.4_linux_amd64.tar.gz"
        sha256 "72f3e02ae30d6e492876a2a7b9682873e892e6df37555bb31a44a20e42dd7327"

        def install
          bin.install "sp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.4/sp_0.1.4_linux_arm64.tar.gz"
        sha256 "22e72ae3152d485aa52b665ed6aa7fba59d66e145a7c58282adac47c1eebc0fe"

        def install
          bin.install "sp"
        end
      end
    end
  end

  test do
    system "#{bin}/sp version"
  end
end
