# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sp < Formula
  desc "Sourceplane CLI - Infrastructure as Code orchestration"
  homepage "https://github.com/sourceplane/sourceplane"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.2.2/sp_0.2.2_darwin_amd64.tar.gz"
      sha256 "452a2e493028373c1fe153a931d6cc3f76e45b20c2016ff7154fd9c4680b429e"

      def install
        bin.install "sp"
      end
    end
    on_arm do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.2.2/sp_0.2.2_darwin_arm64.tar.gz"
      sha256 "e209131d076eb41f609420f9ba581bcce9fd966d3a812c4c7ee0fb9d0a25d03c"

      def install
        bin.install "sp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.2.2/sp_0.2.2_linux_amd64.tar.gz"
        sha256 "438bc5c6799028bc13561d24d12cd7ad4cb25b144aef42e61aa94fe4cde90a25"

        def install
          bin.install "sp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.2.2/sp_0.2.2_linux_arm64.tar.gz"
        sha256 "0eaa364c5a8b872a9b62a4a1e893f5555d70b8f326543fd0fb081568ffb75673"

        def install
          bin.install "sp"
        end
      end
    end
  end

  test do
    system "#{bin}/sp version"
  end
end
