# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thinci < Formula
  desc "Thin-CI - Lightweight CI orchestrator"
  homepage "https://github.com/sourceplane/sourceplane"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.2.0/thinci_0.2.0_darwin_amd64.tar.gz"
      sha256 "e8a9e7dc91b8a4284a0f3e70dddb65ef47484faef13820d573605d47efe3ab78"

      def install
        bin.install "thinci"
      end
    end
    on_arm do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.2.0/thinci_0.2.0_darwin_arm64.tar.gz"
      sha256 "ddcf8fa67a8e0729f0f3300d733538d895eb4067197f18950a617021588dc0cf"

      def install
        bin.install "thinci"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.2.0/thinci_0.2.0_linux_amd64.tar.gz"
        sha256 "d1caebd450ab1655600e0115ad78227a9274a3e09005729ab6df7d6ee931c148"

        def install
          bin.install "thinci"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.2.0/thinci_0.2.0_linux_arm64.tar.gz"
        sha256 "cd36421a3adcd35318e511cf5e1ff75616686669fd966112b51eeb849df9b64d"

        def install
          bin.install "thinci"
        end
      end
    end
  end

  test do
    system "#{bin}/thinci version"
  end
end
