# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thinci < Formula
  desc "Thin-CI - Lightweight CI orchestrator"
  homepage "https://github.com/sourceplane/sourceplane"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.4/thinci_0.1.4_darwin_amd64.tar.gz"
      sha256 "f2d2e9e923a2a2181280393c84c7a1ac73b90211c48dbc031f9bd1fe937cabb3"

      def install
        bin.install "thinci"
      end
    end
    on_arm do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.4/thinci_0.1.4_darwin_arm64.tar.gz"
      sha256 "f3cc718d37133b4cba1a1860796efefbf93f481a892fbf148816fec122d5677b"

      def install
        bin.install "thinci"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.4/thinci_0.1.4_linux_amd64.tar.gz"
        sha256 "dc983afa0ad7efd6bdc762038a91a78d94831ca0aad1c0be5d8e471d92ac2459"

        def install
          bin.install "thinci"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.4/thinci_0.1.4_linux_arm64.tar.gz"
        sha256 "f9d630b5360c488ac3ea0ed5548ef81306b7e78c19e2a58856771f79a09b6d95"

        def install
          bin.install "thinci"
        end
      end
    end
  end

  test do
    system "#{bin}/thinci version"
  end
end
