# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thinci < Formula
  desc "Thin-CI - Lightweight CI orchestrator"
  homepage "https://github.com/sourceplane/sourceplane"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.1/thinci_0.1.1_darwin_amd64.tar.gz"
      sha256 "9348519c32ce79f70f9451a80d11b288ea4a9994448718754c1bc500383e3788"

      def install
        bin.install "thinci"
      end
    end
    on_arm do
      url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.1/thinci_0.1.1_darwin_arm64.tar.gz"
      sha256 "d200190df62d2c50eb1182a55cdb10f1f72d9389255725fba524849a8cba3bb6"

      def install
        bin.install "thinci"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.1/thinci_0.1.1_linux_amd64.tar.gz"
        sha256 "6678f8f375253d60c558ed3ca2e90139818f3d7ba2b07efa9f88d1566fa41346"

        def install
          bin.install "thinci"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/sourceplane/releases/download/v0.1.1/thinci_0.1.1_linux_arm64.tar.gz"
        sha256 "08c5a5635ff49fcc3a58d95e7e9a246c00abecebc6799c48716f0df4973ba1bd"

        def install
          bin.install "thinci"
        end
      end
    end
  end

  test do
    system "#{bin}/thinci version"
  end
end
