# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thin < Formula
  desc "Lightweight CLI that executes provider-native tools"
  homepage "https://github.com/sourceplane/thin"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/sourceplane/thin/releases/download/v0.1.2/thin_Darwin_x86_64.tar.gz"
      sha256 "1266ccc1cf1d73534619bf9d99dd31b326277775a1bb6ecee811a65b7a162295"

      def install
        bin.install "thin"
      end
    end
    on_arm do
      url "https://github.com/sourceplane/thin/releases/download/v0.1.2/thin_Darwin_arm64.tar.gz"
      sha256 "04b0e799ac3a5f28344a320f306151d863dfcd44d92cdb085bfb7ec78b9f0265"

      def install
        bin.install "thin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/thin/releases/download/v0.1.2/thin_Linux_x86_64.tar.gz"
        sha256 "269cf38b311fdbb3499109f9150a5e75f1a57e44b7aa19c1e5c85edc90db012a"

        def install
          bin.install "thin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/thin/releases/download/v0.1.2/thin_Linux_arm64.tar.gz"
        sha256 "9677fb31b68119cf791dfc9e7cf0acfce2698a5ef24fc9cb40338c1ffe62d4a4"

        def install
          bin.install "thin"
        end
      end
    end
  end

  test do
    system "#{bin}/thin", "version"
  end
end
