# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thin < Formula
  desc "Lightweight CLI that executes provider-native tools"
  homepage "https://github.com/sourceplane/thin"
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/sourceplane/thin/releases/download/v0.1.3/thin_Darwin_x86_64.tar.gz"
      sha256 "0d03d2b48c9e28add4dbe82ec6b79b12c80cb6e1fa448bb886044297d593c6d7"

      def install
        bin.install "thin"
      end
    end
    on_arm do
      url "https://github.com/sourceplane/thin/releases/download/v0.1.3/thin_Darwin_arm64.tar.gz"
      sha256 "1225be8550b7cc7cf999c51d2b266f3bf74699886e6c1fe063952e5085d1ed59"

      def install
        bin.install "thin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/thin/releases/download/v0.1.3/thin_Linux_x86_64.tar.gz"
        sha256 "45e8877f9ccd0c6aa04df4d40e8a062dacf72efc845a23e2f28dcef3ee560470"

        def install
          bin.install "thin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sourceplane/thin/releases/download/v0.1.3/thin_Linux_arm64.tar.gz"
        sha256 "21f04998ba56c45001610d5fcbabb83484d6f3ddc1153b433fcfe72ed6f75c45"

        def install
          bin.install "thin"
        end
      end
    end
  end

  test do
    system "#{bin}/thin", "version"
  end
end
